resolver: lts-16.20
packages:
- 'massiv/'
- 'massiv-test/'
flags: {}
extra-deps:
- primitive-0.7.1.0
- pvar-1.0.0.0@sha256:3d4a6855b0960baee78f6956f082eb8aa1cede52d2955b7faef186d1133f7964,1893
#- ../haskell-scheduler/scheduler
- github: lehins/haskell-scheduler
  commit: 64ac5947a2ba07d2eca9c077f81f33c20d646f21
  subdirs:
    - scheduler
